
title: La cucina di Lodi
title-img: /img/logo_nuovo.png
email: cucina.di.lodi@gmail.com
tagline:             'Pensieri, ricette...'
description: #> # this means to ignore newlines until "baseurl:"
  Dal 1987 Pasta Fresca e Corsi di Cucina
baseurl: "" # the subpath of your site, e.g. /blog
url: http://cucina-di-lodi.com # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

paginate:            4
paginate_path: "/blog/page:num/"
excerpt_separator: <!--continua-->


copyright: Copyright Â© 1987 - 2017 LODI. Tutti i diritti riservati.
credits: Site based on Jekyll and Bootstrap.
#add link to gioele github

collections:
    pasta:
    carosello:
    evidenza:
    corsi:

# ----------------------- #
#         Contacts        #
# ----------------------- #
#most of the time title and icon can be the same, but icon for mail was envelope so I divided it
social: 
  - title: Mail
    icon: envelope
    url: "&#x6d;&#97;&#x69;&#108;&#116;&#111;&#x3a;&#x63;&#x75;&#x63;&#105;&#x6e;&#x61;&#x2e;&#x64;&#x69;&#46;&#108;&#111;&#100;&#x69;&#x40;&#x67;&#109;&#x61;&#105;&#x6c;&#x2e;&#99;&#111;&#109;"
  - title: facebook
    icon: facebook
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: youtube
    icon: youtube
    url: https://www.youtube.com/channel/UCTFKEThoXGVaZuNA3Clviwg


# Build settings
markdown: kramdown
theme: jekyll-paginate #minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .gitignore

